[package]
name = "bitonic_sorter"
version = "0.1.0"
authors = ["KaitoKoike <kaikai.poteti@keio.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.6"
rand_pcg="0.1"
rayon="1.0"
num_cpus="1.0"

